<?php

return [
    [
        'key'   => 'sales.payments',
        'name'  => 'Payments',
        'route' => 'admin.sales.payments.index',
        'sort'  => 8,
        'icon'  => '',
    ], [
        'key'            => 'shipments',
        'name'           => 'Shipments',
        'route'          => 'admin.sales.shipments.index',
        'sort'           => 2,
        'icon'           => 'icon-ship',
        'permission_key' => null,
    ], [
        'key'            => 'shipments.to_ship',
        'name'           => 'To Ship',
        'route'          => 'admin.sales.to-ship.index',
        'sort'           => 1,
        'icon'           => '',
        'permission_key' => 'sales.to_ship',
        'shipping_modes' => ['manual_basic'],
    ], [
        'key'            => 'shipments.in_delivery',
        'name'           => 'In Delivery',
        'route'          => 'admin.sales.shipped-orders.index',
        'sort'           => 2,
        'icon'           => '',
        'permission_key' => 'sales.shipped_orders',
        'shipping_modes' => ['manual_basic'],
    ], [
        'key'            => 'shipments.cod_receivables',
        'name'           => 'COD Receivables',
        'route'          => 'admin.sales.cod-receivables.index',
        'sort'           => 3,
        'icon'           => '',
        'permission_key' => 'sales.cod_receivables',
        'shipping_modes' => ['manual_basic'],
    ], [
        'key'            => 'shipments.order_shipments',
        'name'           => 'Order Shipments',
        'route'          => 'admin.sales.shipments.index',
        'sort'           => 1,
        'icon'           => '',
        'permission_key' => 'sales.shipments',
        'shipping_modes' => ['advanced_pro'],
    ], [
        'key'            => 'shipments.shipment_operations',
        'name'           => 'Shipment Ops',
        'route'          => 'admin.sales.shipment-operations.index',
        'sort'           => 2,
        'icon'           => '',
        'permission_key' => 'sales.shipment_operations',
        'shipping_modes' => ['advanced_pro'],
    ], [
        'key'            => 'shipments.cod_settlements',
        'name'           => 'COD Settlements',
        'route'          => 'admin.sales.cod-settlements.index',
        'sort'           => 3,
        'icon'           => '',
        'permission_key' => 'sales.cod_settlements',
        'shipping_modes' => ['advanced_pro'],
    ], [
        'key'            => 'shipments.settlement_batches',
        'name'           => 'Settlement Batches',
        'route'          => 'admin.sales.settlement-batches.index',
        'sort'           => 4,
        'icon'           => '',
        'permission_key' => 'sales.settlement_batches',
        'shipping_modes' => ['advanced_pro'],
    ],
];
