<?php

return [
    [
        'key'  => 'sales.payment_methods.mode',
        'name' => 'Payment Channel',
        'info' => 'Choose whether storefront checkout uses Bagisto native methods or the curated Bangladesh payment set.',
        'sort' => 0,
        'fields' => [
            [
                'name' => 'channel',
                'title' => 'Storefront Payment Channel',
                'type' => 'select',
                'options' => [
                    [
                        'title' => 'Default (native)',
                        'value' => 'default',
                    ],
                    [
                        'title' => 'Custom',
                        'value' => 'custom',
                    ],
                ],
                'channel_based' => true,
                'locale_based' => false,
                'default' => 'default',
            ],
        ],
    ], [
        'key'  => 'sales.payment_methods.bkash_gateway',
        'name' => 'bKash Gateway',
        'info' => 'Direct bKash checkout credentials and endpoint configuration.',
        'sort' => 8,
        'fields' => [
            [
                'name' => 'sandbox',
                'title' => 'Sandbox',
                'type' => 'boolean',
                'channel_based' => true,
                'locale_based' => false,
                'default' => true,
            ], [
                'name' => 'sandbox_base_url',
                'title' => 'Sandbox Base URL',
                'type' => 'text',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'base_url',
                'title' => 'Live Base URL',
                'type' => 'text',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'username',
                'title' => 'Username',
                'type' => 'text',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'password',
                'title' => 'Password',
                'type' => 'password',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'app_key',
                'title' => 'App Key',
                'type' => 'text',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'app_secret',
                'title' => 'App Secret',
                'type' => 'password',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'request_timeout',
                'title' => 'Request Timeout (seconds)',
                'type' => 'text',
                'channel_based' => true,
                'locale_based' => false,
                'default' => 30,
            ], [
                'name' => 'strict_amount_validation',
                'title' => 'Strict Amount Validation',
                'type' => 'boolean',
                'channel_based' => true,
                'locale_based' => false,
                'default' => true,
            ], [
                'name' => 'log_payloads',
                'title' => 'Store Raw Gateway Payloads',
                'type' => 'boolean',
                'channel_based' => true,
                'locale_based' => false,
                'default' => true,
            ],
        ],
    ], [
        'key'  => 'sales.payment_methods.sslcommerz_gateway',
        'name' => 'SSLCOMMERZ Gateway',
        'info' => 'Shared credentials for SSLCOMMERZ-based Bangladesh payment methods.',
        'sort' => 9,
        'fields' => [
            [
                'name' => 'sandbox',
                'title' => 'Sandbox',
                'type' => 'boolean',
                'channel_based' => true,
                'locale_based' => false,
                'default' => true,
            ], [
                'name' => 'store_id',
                'title' => 'Store ID',
                'type' => 'text',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'store_password',
                'title' => 'Store Password',
                'type' => 'password',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'request_timeout',
                'title' => 'Request Timeout (seconds)',
                'type' => 'text',
                'channel_based' => true,
                'locale_based' => false,
                'default' => 30,
            ], [
                'name' => 'strict_amount_validation',
                'title' => 'Strict Amount Validation',
                'type' => 'boolean',
                'channel_based' => true,
                'locale_based' => false,
                'default' => true,
            ], [
                'name' => 'log_payloads',
                'title' => 'Store Raw Gateway Payloads',
                'type' => 'boolean',
                'channel_based' => true,
                'locale_based' => false,
                'default' => true,
            ],
        ],
    ], [
        'key'  => 'sales.payment_methods.sslcommerz_card',
        'name' => 'Bank Card',
        'info' => 'Hosted SSLCOMMERZ card and online banking option.',
        'sort' => 10,
        'fields' => [
            [
                'name' => 'active',
                'title' => 'Status',
                'type' => 'boolean',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'title',
                'title' => 'Title',
                'type' => 'text',
                'validation' => 'required_if:active,1',
                'channel_based' => true,
                'locale_based' => true,
                'default' => 'Bank Card',
            ], [
                'name' => 'description',
                'title' => 'Description',
                'type' => 'textarea',
                'channel_based' => true,
                'locale_based' => true,
                'default' => 'Pay with Bangladeshi bank cards and online banking',
            ], [
                'name' => 'image',
                'title' => 'Logo',
                'type' => 'image',
                'validation' => 'mimes:bmp,jpeg,jpg,png,webp',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'sort',
                'title' => 'Sort Order',
                'type' => 'select',
                'options' => [
                    ['title' => '1', 'value' => 1],
                    ['title' => '2', 'value' => 2],
                    ['title' => '3', 'value' => 3],
                    ['title' => '4', 'value' => 4],
                    ['title' => '5', 'value' => 5],
                    ['title' => '6', 'value' => 6],
                    ['title' => '7', 'value' => 7],
                    ['title' => '8', 'value' => 8],
                ],
                'channel_based' => true,
                'locale_based' => false,
                'default' => 1,
            ],
        ],
    ], [
        'key'  => 'sales.payment_methods.sslcommerz_bkash',
        'name' => 'bKash',
        'info' => 'Direct customers to the bKash gateway inside SSLCOMMERZ.',
        'sort' => 11,
        'fields' => [
            [
                'name' => 'active',
                'title' => 'Status',
                'type' => 'boolean',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'title',
                'title' => 'Title',
                'type' => 'text',
                'validation' => 'required_if:active,1',
                'channel_based' => true,
                'locale_based' => true,
                'default' => 'bKash',
            ], [
                'name' => 'description',
                'title' => 'Description',
                'type' => 'textarea',
                'channel_based' => true,
                'locale_based' => true,
                'default' => 'Pay with bKash',
            ], [
                'name' => 'image',
                'title' => 'Logo',
                'type' => 'image',
                'validation' => 'mimes:bmp,jpeg,jpg,png,webp',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'gateway_code',
                'title' => 'Preferred Gateway Code',
                'type' => 'text',
                'channel_based' => true,
                'locale_based' => false,
                'default' => 'bkash',
            ], [
                'name' => 'sort',
                'title' => 'Sort Order',
                'type' => 'select',
                'options' => [
                    ['title' => '1', 'value' => 1],
                    ['title' => '2', 'value' => 2],
                    ['title' => '3', 'value' => 3],
                    ['title' => '4', 'value' => 4],
                    ['title' => '5', 'value' => 5],
                    ['title' => '6', 'value' => 6],
                    ['title' => '7', 'value' => 7],
                    ['title' => '8', 'value' => 8],
                ],
                'channel_based' => true,
                'locale_based' => false,
                'default' => 2,
            ],
        ],
    ], [
        'key'  => 'sales.payment_methods.sslcommerz_nagad',
        'name' => 'Nagad',
        'info' => 'Direct customers to the Nagad gateway when the SSLCOMMERZ account exposes it.',
        'sort' => 12,
        'fields' => [
            [
                'name' => 'active',
                'title' => 'Status',
                'type' => 'boolean',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'title',
                'title' => 'Title',
                'type' => 'text',
                'validation' => 'required_if:active,1',
                'channel_based' => true,
                'locale_based' => true,
                'default' => 'Nagad',
            ], [
                'name' => 'description',
                'title' => 'Description',
                'type' => 'textarea',
                'channel_based' => true,
                'locale_based' => true,
                'default' => 'Pay with Nagad',
            ], [
                'name' => 'image',
                'title' => 'Logo',
                'type' => 'image',
                'validation' => 'mimes:bmp,jpeg,jpg,png,webp',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'gateway_code',
                'title' => 'Preferred Gateway Code',
                'type' => 'text',
                'channel_based' => true,
                'locale_based' => false,
                'default' => 'nagad',
            ], [
                'name' => 'sort',
                'title' => 'Sort Order',
                'type' => 'select',
                'options' => [
                    ['title' => '1', 'value' => 1],
                    ['title' => '2', 'value' => 2],
                    ['title' => '3', 'value' => 3],
                    ['title' => '4', 'value' => 4],
                    ['title' => '5', 'value' => 5],
                    ['title' => '6', 'value' => 6],
                    ['title' => '7', 'value' => 7],
                    ['title' => '8', 'value' => 8],
                ],
                'channel_based' => true,
                'locale_based' => false,
                'default' => 3,
            ],
        ],
    ], [
        'key'  => 'sales.payment_methods.bkash',
        'name' => 'bKash',
        'info' => 'Direct official bKash checkout option.',
        'sort' => 13,
        'fields' => [
            [
                'name' => 'active',
                'title' => 'Status',
                'type' => 'boolean',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'title',
                'title' => 'Title',
                'type' => 'text',
                'validation' => 'required_if:active,1',
                'channel_based' => true,
                'locale_based' => true,
                'default' => 'bKash',
            ], [
                'name' => 'description',
                'title' => 'Description',
                'type' => 'textarea',
                'channel_based' => true,
                'locale_based' => true,
                'default' => 'Pay directly with bKash',
            ], [
                'name' => 'image',
                'title' => 'Logo',
                'type' => 'image',
                'validation' => 'mimes:bmp,jpeg,jpg,png,webp',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'sort',
                'title' => 'Sort Order',
                'type' => 'select',
                'options' => [
                    ['title' => '1', 'value' => 1],
                    ['title' => '2', 'value' => 2],
                    ['title' => '3', 'value' => 3],
                    ['title' => '4', 'value' => 4],
                    ['title' => '5', 'value' => 5],
                    ['title' => '6', 'value' => 6],
                    ['title' => '7', 'value' => 7],
                    ['title' => '8', 'value' => 8],
                ],
                'channel_based' => true,
                'locale_based' => false,
                'default' => 2,
            ],
        ],
    ], [
        'key'  => 'sales.carriers.courier',
        'name' => 'Courier',
        'info' => 'Bangladesh courier delivery options for home delivery and pick-up.',
        'sort' => 3,
        'fields' => [
            [
                'name' => 'active',
                'title' => 'Status',
                'type' => 'boolean',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'title',
                'title' => 'Title',
                'type' => 'text',
                'validation' => 'required_if:active,1',
                'channel_based' => true,
                'locale_based' => true,
                'default' => 'Courier',
            ], [
                'name' => 'description',
                'title' => 'Description',
                'type' => 'textarea',
                'channel_based' => true,
                'locale_based' => true,
                'default' => 'Courier shipping options',
            ], [
                'name' => 'home_delivery_active',
                'title' => 'Enable Home Delivery',
                'type' => 'boolean',
                'channel_based' => true,
                'locale_based' => false,
                'default' => true,
            ], [
                'name' => 'home_delivery_title',
                'title' => 'Home Delivery Title',
                'type' => 'text',
                'validation' => 'required_if:home_delivery_active,1',
                'channel_based' => true,
                'locale_based' => true,
                'default' => 'Home Delivery',
            ], [
                'name' => 'home_delivery_rate',
                'title' => 'Home Delivery Rate',
                'type' => 'text',
                'validation' => 'required_if:home_delivery_active,1|numeric',
                'channel_based' => true,
                'locale_based' => false,
                'default' => 80,
            ], [
                'name' => 'pickup_active',
                'title' => 'Enable Courier Pick-up',
                'type' => 'boolean',
                'channel_based' => true,
                'locale_based' => false,
                'default' => true,
            ], [
                'name' => 'pickup_title',
                'title' => 'Courier Pick-up Title',
                'type' => 'text',
                'validation' => 'required_if:pickup_active,1',
                'channel_based' => true,
                'locale_based' => true,
                'default' => 'Courier Pick-up',
            ], [
                'name' => 'pickup_rate',
                'title' => 'Courier Pick-up Rate',
                'type' => 'text',
                'validation' => 'required_if:pickup_active,1|numeric',
                'channel_based' => true,
                'locale_based' => false,
                'default' => 40,
            ],
        ],
    ],
];
