<?php

return [
    [
        'key'  => 'sales.payment_methods.bkash_gateway',
        'name' => 'bKash Gateway',
        'info' => 'Direct bKash checkout credentials and endpoint configuration.',
        'sort' => 8,
        'fields' => [
            [
                'name' => 'sandbox',
                'title' => 'Sandbox',
                'type' => 'boolean',
                'channel_based' => true,
                'locale_based' => false,
                'default' => true,
            ], [
                'name' => 'sandbox_base_url',
                'title' => 'Sandbox Base URL',
                'type' => 'text',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'base_url',
                'title' => 'Live Base URL',
                'type' => 'text',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'username',
                'title' => 'Username',
                'type' => 'text',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'password',
                'title' => 'Password',
                'type' => 'password',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'app_key',
                'title' => 'App Key',
                'type' => 'text',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'app_secret',
                'title' => 'App Secret',
                'type' => 'password',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'request_timeout',
                'title' => 'Request Timeout (seconds)',
                'type' => 'text',
                'channel_based' => true,
                'locale_based' => false,
                'default' => 30,
            ], [
                'name' => 'strict_amount_validation',
                'title' => 'Strict Amount Validation',
                'type' => 'boolean',
                'channel_based' => true,
                'locale_based' => false,
                'default' => true,
            ], [
                'name' => 'log_payloads',
                'title' => 'Store Raw Gateway Payloads',
                'type' => 'boolean',
                'channel_based' => true,
                'locale_based' => false,
                'default' => true,
            ],
        ],
    ], [
        'key'  => 'sales.payment_methods.sslcommerz_gateway',
        'name' => 'SSLCommerz Gateway',
        'info' => 'Shared credentials for SSLCommerz-based Bangladesh payment methods.',
        'sort' => 9,
        'fields' => [
            [
                'name' => 'sandbox',
                'title' => 'Sandbox',
                'type' => 'boolean',
                'channel_based' => true,
                'locale_based' => false,
                'default' => true,
            ], [
                'name' => 'store_id',
                'title' => 'Store ID',
                'type' => 'text',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'store_password',
                'title' => 'Store Password',
                'type' => 'password',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'request_timeout',
                'title' => 'Request Timeout (seconds)',
                'type' => 'text',
                'channel_based' => true,
                'locale_based' => false,
                'default' => 30,
            ], [
                'name' => 'strict_amount_validation',
                'title' => 'Strict Amount Validation',
                'type' => 'boolean',
                'channel_based' => true,
                'locale_based' => false,
                'default' => true,
            ], [
                'name' => 'log_payloads',
                'title' => 'Store Raw Gateway Payloads',
                'type' => 'boolean',
                'channel_based' => true,
                'locale_based' => false,
                'default' => true,
            ],
        ],
    ], [
        'key'  => 'sales.payment_methods.sslcommerz',
        'name' => 'SSLCommerz',
        'info' => 'Unified SSLCommerz checkout option for cards, mobile banking, and internet banking.',
        'sort' => 10,
        'fields' => [
            [
                'name' => 'active',
                'title' => 'Status',
                'type' => 'boolean',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'title',
                'title' => 'Title',
                'type' => 'text',
                'validation' => 'required_if:active,1',
                'channel_based' => true,
                'locale_based' => true,
                'default' => 'Pay Online',
            ], [
                'name' => 'description',
                'title' => 'Description',
                'type' => 'textarea',
                'channel_based' => true,
                'locale_based' => true,
                'default' => 'Pay online with cards, mobile banking, and internet banking via SSLCommerz',
            ], [
                'name' => 'image',
                'title' => 'Logo',
                'type' => 'image',
                'validation' => 'mimes:bmp,jpeg,jpg,png,webp',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'sort',
                'title' => 'Sort Order',
                'type' => 'select',
                'options' => [
                    ['title' => '1', 'value' => 1],
                    ['title' => '2', 'value' => 2],
                    ['title' => '3', 'value' => 3],
                    ['title' => '4', 'value' => 4],
                    ['title' => '5', 'value' => 5],
                    ['title' => '6', 'value' => 6],
                    ['title' => '7', 'value' => 7],
                    ['title' => '8', 'value' => 8],
                ],
                'channel_based' => true,
                'locale_based' => false,
                'default' => 1,
            ],
        ],
    ], [
        'key'  => 'sales.payment_methods.bkash',
        'name' => 'bKash',
        'info' => 'Direct official bKash checkout option.',
        'sort' => 11,
        'fields' => [
            [
                'name' => 'active',
                'title' => 'Status',
                'type' => 'boolean',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'title',
                'title' => 'Title',
                'type' => 'text',
                'validation' => 'required_if:active,1',
                'channel_based' => true,
                'locale_based' => true,
                'default' => 'bKash',
            ], [
                'name' => 'description',
                'title' => 'Description',
                'type' => 'textarea',
                'channel_based' => true,
                'locale_based' => true,
                'default' => 'Pay directly with bKash',
            ], [
                'name' => 'image',
                'title' => 'Logo',
                'type' => 'image',
                'validation' => 'mimes:bmp,jpeg,jpg,png,webp',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'sort',
                'title' => 'Sort Order',
                'type' => 'select',
                'options' => [
                    ['title' => '1', 'value' => 1],
                    ['title' => '2', 'value' => 2],
                    ['title' => '3', 'value' => 3],
                    ['title' => '4', 'value' => 4],
                    ['title' => '5', 'value' => 5],
                    ['title' => '6', 'value' => 6],
                    ['title' => '7', 'value' => 7],
                    ['title' => '8', 'value' => 8],
                ],
                'channel_based' => true,
                'locale_based' => false,
                'default' => 2,
            ],
        ],
    ], [
        'key'  => 'sales.carriers.courier',
        'name' => 'Courier',
        'info' => 'District-based delivery charges for checkout.',
        'sort' => 3,
        'fields' => [
            [
                'name' => 'active',
                'title' => 'Status',
                'type' => 'boolean',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'title',
                'title' => 'Title',
                'type' => 'text',
                'validation' => 'required_if:active,1',
                'channel_based' => true,
                'locale_based' => true,
                'default' => 'Courier',
            ], [
                'name' => 'description',
                'title' => 'Description',
                'type' => 'textarea',
                'channel_based' => true,
                'locale_based' => true,
                'default' => 'District-based delivery charges',
            ], [
                'name' => 'default_rate',
                'title' => 'Default Rate',
                'type' => 'text',
                'validation' => 'required_if:active,1|numeric',
                'channel_based' => true,
                'locale_based' => false,
                'default' => 120,
            ], [
                'name' => 'district_rates',
                'title' => 'District Rates',
                'info' => 'Use one district per line in the format District=Rate. Example: Dhaka=60',
                'type' => 'textarea',
                'channel_based' => true,
                'locale_based' => false,
                'default' => "Dhaka=60\nChattogram=120",
            ], [
                'name' => 'dhaka_district',
                'title' => 'Legacy Dhaka District Name',
                'type' => 'text',
                'validation' => 'required_if:active,1',
                'channel_based' => true,
                'locale_based' => false,
                'default' => 'Dhaka',
            ], [
                'name' => 'dhaka_title',
                'title' => 'Legacy Dhaka Title',
                'type' => 'text',
                'validation' => 'required_if:active,1',
                'channel_based' => true,
                'locale_based' => true,
                'default' => 'Dhaka Delivery',
            ], [
                'name' => 'dhaka_rate',
                'title' => 'Legacy Dhaka Rate',
                'type' => 'text',
                'validation' => 'required_if:active,1|numeric',
                'channel_based' => true,
                'locale_based' => false,
                'default' => 60,
            ], [
                'name' => 'outside_dhaka_title',
                'title' => 'Legacy Outside Dhaka Title',
                'type' => 'text',
                'validation' => 'required_if:active,1',
                'channel_based' => true,
                'locale_based' => true,
                'default' => 'Outside Dhaka Delivery',
            ], [
                'name' => 'outside_dhaka_rate',
                'title' => 'Legacy Outside Dhaka Rate',
                'type' => 'text',
                'validation' => 'required_if:active,1|numeric',
                'channel_based' => true,
                'locale_based' => false,
                'default' => 120,
            ],
        ],
    ],
];
